### ISSUE TITLE
Stopped working for valorant

### ISSUE THREAD

**Issue by zaBees** [RoniRaad/Omni-Account-Manager#61]
I just shows No data available and can't be used to login
![image](https://github.com/RoniRaad/Omni-Account-Manager/assets/45898130/d3865bc4-6476-47e9-a8d9-5cb17a5c6d18)

**Comment by RoniRaad** [comment]
This should be fixed in the latest version. Please let me know if you are still having issues.

**Comment by tanishqmanuja** [comment]
Is it fixed?
![image](https://github.com/user-attachments/assets/b1e1da0d-0532-40fc-ae34-4fe485b2d4e2)
